### ISSUE TITLE
Mise à jour des styles BJCP

### ISSUE THREAD

**Issue by martync** [martync/zython#2]
Ajouter les nouveaux styles BJCP
https://www.bjcp.org/bjcp-style-guidelines/

- Utiliser l'attribut `guide` du modèle `brew.models.BeerStyle` pour différencier les années
- Dans `brew.forms.RecipeForm` filtrer les styles sur la dernière année. Pour la modification d'une recette existante ayant un style d'une année précédente, il faut que ce choix apparaisse et soit sélectionné
- Dans `brew.views.style.StyleListView`, afficher seulement les styles de la dernière année

**Comment by valentinbeer** [comment]
Salut, tu peux me l'assigner et me fournir quelques ressources s'il te plaît ?

**Comment by martync** [comment]
Dans ce repo https://github.com/bjcp-brasil/styleguide-2021 on trouve le BJCP 2021 parsé en JSON, XML et YAML. 

Il faut que le fichier à fournir soit au format JSON dans ce modèle là : https://github.com/martync/zython/blob/main/apps/brew/fixtures/initial_data.json

Description des champs : 

 * `name` : (text) Nom du style. Ex : "Lite American Lager"
 * `number` : (int) Numéro du style BJCP. Ex : pour le style 4B, le numéro sera 4
 * `subnumber` : (text) Lettre du style BJCP. Ex : pour le style 4B, le numéro sera B
 * `category` : (text) Catégorie du style. Ex : "Light Lager"
 * `original_gravity_max` et `original_gravity_min` : (decimal X.XXX) Densitées originales. Ex : 1.078
 * `final_gravity_max` et `final_gravity_min` : (decimal X.XXX) Densitées finales. Ex : 1.008
 * `color_max` et `color_min` : (decimal X.X) Couleurs exprimées en EBC. Ex : 5.9
 * `alcohol_max` et `alcohol_min` : (decimal X.X) Alcool en degré plato Ex : 11.5
 * `bitterness_max` et `bitterness_min` : (int) IBU 
 * `guide` : (text) Nom du guide BJCP. Ex : "BJCP 2021"
 * `examples`, `ingredients`, `profile`, `description` : (long text)

**Comment by martync** [comment]
L'import des styles 2021 est quasiment  prêt, il ne reste plus qu'à écrire quelques tests. 

J'ai dû apporter quelques modifications aux normes choisies par la BJCP pour le nommage des styles "Provisional Styles". Au lieu d'utiliser les code X1...X5, j'ai utilisé 991...995. Cette catégorie là faisait exception car toutes les autres catégories ont des id numériques. 

Certains styles ont des indicateur (densité, abv...) plus complexes : 
* L'ABV des Saison https://github.com/bjcp-brasil/styleguide-2021/blob/main/bjcp-2021.json#L4767 
* La densité de certains styles spéciaux n'est pas renseignée. Pour l'instant la valeur de ces densité est fixée à 0 puisqu'une valeur nulle pourrait provoquer des erreurs sur les fiches recettes. Ce point reste à être géré au cas particulier dans un second temps. 

Pour que les anciens styles continuent de s'afficher lorsqu'on modifie une recette existante, j'ai fait apparaître le style en haut de la liste. 
![Capture d’écran 2022-11-30 à 11 43 17](https://user-images.githubusercontent.com/240125/204775661-207e6c56-5f13-45df-a847-01e3a9fab65c.png)
